language: cpp

dist: trusty
sudo: required

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update

script: 'mkdir build && cd build && cmake .. && make'

notifications:
  email: false
