language: cpp

dist: trusty
sudo: required

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libopencv-dev

script: './debug.sh'

notifications:
  email: false
